name: QuaGroup
version: 1.8
date: 2013-08-16
description: |
    Computations with quantum groups

authors:
    - name: Willem Adriaan de Graaf
      url: http://www.science.unitn.it/~degraaf

maintainers:
    - name: Willem Adriaan de Graaf
      url: http://www.science.unitn.it/~degraaf

GAP: ">=4.8"

www: https://gap-packages.github.io/quagroup/
readme: README.md
packageinfo: https://gap-packages.github.io/quagroup/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/quagroup/releases/download/v1.8/quagroup-1.8.tar.gz

abstract: |
    The package <span class="pkgname">QuaGroup</span> contains                  functionality for working with quantized enveloping algebras                 of finite-dimensional semisimple Lie algebras.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    quantum groups.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>dG13</span>]   <b class='BibAuthor'>de Graaf, W. A.</b>,
     <i class='BibTitle'>QuaGroup, Computations with quantum groups,
             Version 1.8</i>
     (<span class='BibYear'>2013</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/quagroup/">https://gap-packages.github.io/quagroup/</a></span>.
    </p>
    

bibtex: |
    @misc{ QuaGroup1.8,
      author =           {de Graaf, W. A.},
      title =            {{QuaGroup}, Computations with quantum groups, {V}ersion 1.8},
      month =            {Aug},
      year =             {2013},
      note =             {Refereed GAP package},
      howpublished =     {\href {https://gap-packages.github.io/quagroup/} {\texttt{https://gap-packages.github.io/}\discretionary {}{}{}\texttt{quagroup/}}},
      keywords =         {quantum groups},
      printedkey =       {dG13}
    }

