name: QuaGroup
version: 1.8.3
date: 2022-02-10
description: |
    Computations with quantum groups

authors:
    - name: Willem Adriaan de Graaf
      url: http://www.science.unitn.it/~degraaf

maintainers:
    - name: Willem Adriaan de Graaf
      url: http://www.science.unitn.it/~degraaf
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.8"

www: https://gap-packages.github.io/quagroup/
readme: README.md
packageinfo: https://gap-packages.github.io/quagroup/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/quagroup/releases/download/v1.8.3/quagroup-1.8.3.tar.gz

abstract: |
    The package <span class="pkgname">QuaGroup</span> contains                  functionality for working with quantized enveloping algebras                 of finite-dimensional semisimple Lie algebras.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    quantum groups.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>GT22</span>]   <b class='BibAuthor'>de Graaf, W. A. and GAP Team, T.</b>,
     <i class='BibTitle'>QuaGroup, Computations with quantum groups,
             Version 1.8.3</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/quagroup/">https://gap-packages.github.io/quagroup/</a></span>.
    </p>
    

bibtex: |
    @misc{ QuaGroup1.8.3,
      author =           {de Graaf, W. A. and GAP Team, T.},
      title =            {{QuaGroup},    Computations   with   quantum   groups,
                          {V}ersion 1.8.3},
      month =            {Feb},
      year =             {2022},
      note =             {Refereed GAP package},
      howpublished =     {\href       {https://gap-packages.github.io/quagroup/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{quagroup/}}},
      keywords =         {quantum groups},
      printedkey =       {GT22}
    }

